export * from "./Hero";
export * from "./Footer";
export * from "./Feedback";
export * from "./NavigationButton";
export * from "./Navbar";
export * from "./SpecialOffers";
export * from "./CoursesList";
export * from "./QuizPage";
export * from "./DetailCourseLayout"